# Generated by Django 5.2.4 on 2025-07-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_caption', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
