# Generated by Django 5.2.4 on 2025-07-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginal', models.ImageField(upload_to='original/')),
                ('compres', models.ImageField(blank=True, null=True, upload_to='compres/')),
            ],
        ),
    ]
